Install and import Numpy

In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
print(np.__version__)

2.1.3


**Compare Python list and numpy array**

In [10]:
import time
import numpy as np # no need to import again

n = 1_000_00 # 1000000 
py_list = list(range(n))
np_array = np.arange(n)

# print(len(py_list))
# print(len(np_array))

# print(py_list[0:5])
# print(np_array[0:5])

# Python List
t1 = time.time()
py_result = [x*2 for x in py_list] # Multiply each element by 2
t2 = time.time()

# Numpy array (same operation)
t3 = time.time()
np_result = np_array * 2
t4 = time.time()

print("List Time: ", t2 - t1)
print("Numpy Time: ", t4 - t3)

List Time:  0.007505178451538086
Numpy Time:  0.00033283233642578125


In [ ]:
arr1 = np.array([1,2,3,4,5]) #1D
arr2 = np.array([[1,2.3,3], [4,5,6]]) #2D
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

# In numpy if you change one element data type then automatically all the values in that array will be converted to that type

print("1D array:", arr1) # 1D array is called as Vector
print("\n2D array:\n", arr2) # 2D arrays are called as Matrices ml datasets are typically in 2D Arrays.
print("\n3D array:\n", arr3)

1D array: [1 2 3 4 5]

2D array:
 [[1.  2.3 3. ]
 [4.  5.  6. ]]

3D array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
print(type(arr1))

<class 'numpy.ndarray'>


In [21]:
# Array attributes
print("shape:", arr2.shape)
print("Dimensions: ", arr2.ndim)
print("Data Type:", arr2.dtype)
print("Data Type:", arr3.dtype)
print("Total Elements:", arr2.size)

shape: (2, 3)
Dimensions:  2
Data Type: float64
Data Type: int64
Total Elements: 6


*Creating special Arrays*

In [ ]:
# 🧠 Why we use zeros(), ones(), eye(), random.rand() in ML
# In Machine Learning, we constantly need to create arrays for:
# storing data
# initializing weights
# building matrices
# testing models
# These functions are just quick ways to create arrays without typing values manually

zeros = np.zeros((3,3)) 
ones = np.ones((3,3))
eye = np.eye(3) # identity Matrix if you multiply this matrix with any matrix you will again get identity matrix only.
random_arr = np.arange(0,10,2)

print(zeros)
print("-----")
print(ones)
print("-----")
print(eye)
print("-----")
print(random_arr)




[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-----
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-----
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----
[0 2 4 6 8]


**Indexing and slicing**

In [32]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70,80,90]])

print(arr)
print("-----")

print(arr[0,2]) # To access the perticular Element 
print("-----")
print(arr[0]) # To access the row 
print("-----")
print(arr[:,0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
-----
30
-----
[10 20 30]
-----
[10 40 70]


**Array Operations**

In [34]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition:", a+b)
print("Substraction:", a-b)
print("Multiplication: ", a * b)
print("Division: ", a / b)
print("Dot Product: ", np.dot(a,b))
print("Cross Product: ", np.cross(a,b))

Addition: [5 7 9]
Substraction: [-3 -3 -3]
Multiplication:  [ 4 10 18]
Division:  [0.25 0.4  0.5 ]
Dot Product:  32
Cross Product:  [-3  6 -3]
